### ISSUE TITLE
[DOC] - file should be removed from LICENSE.md link

### ISSUE THREAD

**Issue by bishal7679** [naomis-novas/handbook#7]
### What is incorrect in the documentation?

![Screenshot (147)](https://user-images.githubusercontent.com/70086051/175575596-cc9b41a0-ed85-429d-ab75-2186d76f18ec.png)

### What should that text say?

![Screenshot (148)](https://user-images.githubusercontent.com/70086051/175576541-0beebab6-9c95-4ad5-89ef-90f373738ebd.png)

**Comment by naomi-lgbt** [comment]
I don't believe this change needs to be made. Could you explain further?

**Comment by bishal7679** [comment]
@naomi-lgbt 
file should be placed outside the LICENSE.md link
Its looking not so good 
It should be 
[LICENSE.md] file.
Not [LICENCE.md file]
